<script lang="ts">
	import { onMount } from 'svelte';
	import WorkbenchPage from '$lib/components/dashboard/WorkbenchPage.svelte';
	import MetricTile from '$lib/components/dashboard/MetricTile.svelte';
	import SignalRibbon from '$lib/components/dashboard/SignalRibbon.svelte';
	import TelemetryPlot from '$lib/components/dashboard/TelemetryPlot.svelte';
	import MultiLine from '$lib/components/dashboard/MultiLine.svelte';
	import GaugeRing from '$lib/components/dashboard/GaugeRing.svelte';
	import Panel from '$lib/components/dashboard/Panel.svelte';
	import { api } from '$lib/services/api'; import { connectLive } from '$lib/services/websocket';
	let monitoring = $state(false); let channel = $state('CONNECTING'); let error = $state('');
	let live = $state({ hr: 74, spo2: 98.2, ecg_sqi: 84, ppg_sqi: 76 });
	const hr = [68,70,69,73,71,74,77,75,73,72,74,76,78,75,74,73,74,76,75,74,73,74,74,75];
	const spo2 = [98.4,98.2,98.1,98.3,98.1,98,97.9,98.2,98.4,98.3,98.2,98.1,98.2,98.3,98.4,98.2,98.1,98.2,98.2,98.3,98.1,98.2,98.3,98.2];
	onMount(() => { const socket = connectLive('client_01', { onopen: () => channel = 'LIVE', onclose: () => channel = 'CLOSED', onerror: () => channel = 'LOCAL DEMO', onmessage: (event) => { try { live = { ...live, ...JSON.parse(event.data) }; } catch {} } }); return () => socket.close(); });
	async function toggle() { error = ''; try { if (monitoring) await api.monitoring.stopSimulator('client_01'); else await api.monitoring.startSimulator('client_01'); monitoring = !monitoring; } catch (e) { error = e instanceof Error ? e.message : 'Simulator action failed'; } }
</script>
<svelte:head><title>Observe | NHM</title></svelte:head>
<WorkbenchPage eyebrow="01 / OBSERVE" title="Read the whole signal." description="A single clinical cockpit for the wearable stream: raw traces, quality gates, physiology, and the context behind every downstream inference.">
	<div class="command"><span><i class:live={channel === 'LIVE'}></i> {channel}</span><span>SESSION / DEMO-24H</span><span>DEVICE / ESP32_001</span><button class:stop={monitoring} onclick={toggle}>{monitoring ? 'STOP STREAM' : 'START STREAM'} ↗</button></div>{#if error}<div class="error">{error}</div>{/if}
	<div class="metrics"><MetricTile label="Heart rate" value={live.hr} unit="BPM" detail="BASELINE 68—82" tone="rose" trend="+1.8%" values={hr} /><MetricTile label="SpO₂" value={live.spo2.toFixed(1)} unit="%" detail="NO DESATURATION" tone="cyan" trend="STABLE" values={spo2} /><MetricTile label="ECG / PPG SQI" value={Math.round((live.ecg_sqi + live.ppg_sqi) / 2)} unit="%" detail="QUALITY GATE / GOOD" values={[78,80,82,81,84,83,84,82,84]} /><MetricTile label="Anomaly risk" value="0.08" detail="NORMAL / LIMIT 0.70" tone="amber" trend="LOW" values={[.09,.1,.08,.09,.07,.08,.08,.08]} /></div>
	<SignalRibbon duration="LAST 60 MIN" channels={[{ label: 'ECG', color: '#fb7185', mode: 'ecg', value: String(live.hr), unit: 'BPM' }, { label: 'PPG', color: '#38bdf8', mode: 'ppg', value: String(live.ppg_sqi), unit: 'SQI' }, { label: 'SpO₂', color: '#2bb8b0', mode: 'spo2', value: live.spo2.toFixed(1), unit: '%' }]} />
	<div class="grid two"><Panel eyebrow="PHYSIOLOGY / 24 H" title="Trend envelope" note="SIMULATED / BACKEND READY"><MultiLine series={[{ name: 'Heart rate', color: '#fb7185', values: hr }, { name: 'SpO₂ × 0.75', color: '#38bdf8', values: spo2.map((v) => v * .75) }]} xLabels={['00:00','04:00','08:00','12:00','16:00','20:00','NOW']} yMin={50} yMax={100} yLabel="BPM / %" /></Panel><Panel eyebrow="QUALITY / SQI" title="Quality gate" note="ECG 60% · PPG 40%"><div class="quality"><GaugeRing value={live.ecg_sqi} label="ECG SQI" color="#2bb8b0" size={112} /><GaugeRing value={live.ppg_sqi} label="PPG SQI" color="#38bdf8" size={112} /><GaugeRing value={Math.round((live.ecg_sqi + live.ppg_sqi) / 2)} label="OVERALL" color="#a78bfa" size={112} /></div><div class="quality-foot"><span><i class="ok"></i> Reliable for ML</span><span>Missing fraction / 0.6%</span></div></Panel></div>
	<div class="grid two lower"><Panel eyebrow="LIVE / ELECTRICAL" title="ECG morphology" note="AD8232 · 250 HZ"><TelemetryPlot label="Filtered ECG · R-peak detector" value={live.hr} unit="BPM" detail="BANDPASS 0.5—40HZ · NOTCH 50HZ" /></Panel><Panel eyebrow="LIVE / OPTICAL" title="PPG pulse" note="MAX30102 · 50 HZ"><TelemetryPlot label="Filtered PPG · pulse interval" mode="ppg" color="#38bdf8" value={live.spo2.toFixed(1)} unit="%" detail="PERFUSION / STABLE" /></Panel></div>
</WorkbenchPage>
<style>
	.command{display:flex;align-items:center;flex-wrap:wrap;gap:22px;padding:12px 0;border-block:1px solid rgba(148,163,184,.14);color:#64748b;font:8px 'JetBrains Mono',monospace;letter-spacing:.1em}.command i{display:inline-block;width:6px;height:6px;margin-right:6px;border-radius:50%;background:#64748b}.command i.live{background:#2bb8b0;box-shadow:0 0 9px #2bb8b0}.command button{margin-left:auto;padding:10px 13px;border:1px solid #2bb8b0;color:#03100f;background:#2bb8b0;font:8px 'JetBrains Mono',monospace;letter-spacing:.1em;cursor:pointer}.command button.stop{border-color:#fb7185;background:#fb7185}.error{padding:11px;margin-top:14px;border-left:2px solid #fb7185;color:#fecdd3;background:#3b101a;font:9px 'JetBrains Mono',monospace}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:16px 0 8px}.grid{display:grid;gap:8px;margin-top:8px}.grid.two{grid-template-columns:1.25fr .75fr}.quality{display:flex;justify-content:space-around;align-items:center;gap:10px;padding:6px 0 16px}.quality-foot{display:flex;justify-content:space-between;padding-top:13px;border-top:1px solid rgba(148,163,184,.12);color:#64748b;font:8px 'JetBrains Mono',monospace}.quality-foot i{display:inline-block;width:6px;height:6px;margin-right:5px;border-radius:50%}.quality-foot i.ok{background:#2bb8b0;box-shadow:0 0 7px #2bb8b0}.lower{margin-top:8px}.lower :global(.plot-panel){border:0}.lower :global(.panel-body){padding:0}.lower :global(.plot-panel header){padding-top:10px}.lower :global(.plot-panel footer){padding-bottom:12px}@media(max-width:1000px){.metrics{grid-template-columns:repeat(2,1fr)}.grid.two{grid-template-columns:1fr}}@media(max-width:520px){.metrics{grid-template-columns:1fr 1fr}.quality{flex-wrap:wrap}.quality :global(.gauge-wrap){width:90px!important;height:90px!important}.command button{margin-left:0}}
</style>
