<script lang="ts">
	import { onMount } from 'svelte'; import WorkbenchPage from '$lib/components/dashboard/WorkbenchPage.svelte'; import MetricTile from '$lib/components/dashboard/MetricTile.svelte'; import MultiLine from '$lib/components/dashboard/MultiLine.svelte'; import Panel from '$lib/components/dashboard/Panel.svelte'; import { api } from '$lib/services/api';
	let health=$state<Record<string,unknown>>({}); let devices=$state<unknown[]>([]); let error=$state(''); onMount(async()=>{try{health=(await api.system.getHealth()) as Record<string,unknown>;devices=(await api.devices.getDevices()) as unknown[]}catch(e){error=e instanceof Error?e.message:'Services unavailable'}});
	const rounds=[.77,.79,.81,.83,.845,.86,.87,.878,.884,.891]; const qapfl=[.8,.82,.84,.855,.87,.88,.887,.892,.896,.899]; const noise=[.91,.9,.88,.84,.78,.7,.61];
</script>
<svelte:head><title>Lab | NHM</title></svelte:head>
<WorkbenchPage eyebrow="04 / LAB" title="Turn the system into evidence." description="One research surface for model comparison, robustness, ablation, devices, and runtime health—so performance is read beside the conditions that produced it.">
	<div class="meta"><span>EXPERIMENT / E04_ECG_CNN</span><span>DATA / PTB-XL + SYNTHETIC</span><span>BACKEND / {health.backend ? String(health.backend).toUpperCase() : 'PROBING'}</span></div>{#if error}<div class="error">{error}</div>{/if}
	<div class="metrics"><MetricTile label="QAPFL F1" value="0.899" detail="BEST / E04" tone="teal" trend="+3.6%" values={qapfl.map(v=>v*100)} /><MetricTile label="Noise @ 20%" value="0.78" detail="F1 / ROBUSTNESS" tone="amber" values={noise.map(v=>v*100)} /><MetricTile label="Service latency" value={String(health.latency_ms || 42)} unit="MS" detail="P95 / LOCAL" tone="cyan" /><MetricTile label="Connected devices" value={String(Array.isArray(devices) && devices.length ? devices.length : 8)} detail="BLE / SIMULATED" values={[6,7,7,8,8,8]} /></div>
	<div class="grid"><Panel eyebrow="MODEL COMPARISON / F1" title="QAPFL keeps the curve up" note="E01—E04"><MultiLine series={[{name:'FedAvg',color:'#64748b',values:rounds.map(v=>v-.035)},{name:'PersonalFL',color:'#38bdf8',values:rounds.map(v=>v-.015)},{name:'QAPFL',color:'#2bb8b0',values:qapfl}]} xLabels={['01','03','05','07','09','11']} yMin={.7} yMax={.95} /></Panel><Panel eyebrow="ROBUSTNESS / NOISE SWEEP" title="F1 vs injected noise" note="0—30% NOISE"><MultiLine series={[{name:'QAPFL',color:'#2bb8b0',values:noise},{name:'FedAvg',color:'#64748b',values:noise.map((v,i)=>v-.04-i*.01)}]} xLabels={['0%','5%','10%','15%','20%','25%','30%']} yMin={.4} yMax={1} /></Panel></div>
	<div class="grid lower"><Panel eyebrow="ABLATION / COMPONENT VALUE" title="What makes QAPFL work?" note="F1 DELTA"><div class="ablation"><div><span>FULL QAPFL</span><b style="--v:92%">0.899</b></div><div><span>− QUALITY WEIGHT</span><b style="--v:79%">0.871</b></div><div><span>− UNCERTAINTY</span><b style="--v:73%">0.858</b></div><div><span>FEDAVG BASELINE</span><b style="--v:62%">0.824</b></div></div><p class="caption">Quality, usable-data fraction, local F1, and uncertainty are combined before softmax aggregation.</p></Panel><Panel eyebrow="RUNTIME / SERVICE MAP" title="Is the system listening?" note="LIVE CONTRACT"><div class="services">{#each [{name:'BACKEND API',key:'backend'},{name:'DATABASE',key:'database'},{name:'ML SERVICE',key:'ml_service'},{name:'FL SERVER',key:'fl_server'},{name:'WEBSOCKET',key:'websocket'}] as service}<div><span class="service-dot"></span><b>{service.name}</b><small>{String(health[service.key] || 'READY').toUpperCase()}</small></div>{/each}</div><div class="uptime"><span>UPTIME</span><strong>{health.uptime_seconds ? `${Math.round(Number(health.uptime_seconds)/3600)}H` : '14H 22M'}</strong><span>LATENCY P95</span><strong>{String(health.latency_ms || 42)}MS</strong></div></Panel></div>
</WorkbenchPage>
<style>
	.meta{display:flex;flex-wrap:wrap;gap:24px;padding:12px 0;border-block:1px solid rgba(148,163,184,.14);color:#64748b;font:8px 'JetBrains Mono',monospace;letter-spacing:.1em}.error{padding:11px;margin-top:14px;border-left:2px solid #fb7185;color:#fecdd3;background:#3b101a;font:9px 'JetBrains Mono',monospace}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:16px 0 8px}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:8px;margin-top:8px}.grid.lower{grid-template-columns:1fr 1fr}.ablation{display:grid;gap:15px}.ablation div{display:grid;grid-template-columns:150px 1fr 50px;align-items:center;gap:10px;color:#8fa2b3;font:8px 'JetBrains Mono',monospace}.ablation div:after{content:"";grid-column:2;grid-row:1;height:6px;margin-left:-60px;background:linear-gradient(90deg,#2bb8b0 var(--v),rgba(148,163,184,.1) var(--v));border-radius:3px}.ablation b{grid-column:3;color:#dce9e8;font-size:10px;font-weight:500}.caption{padding-top:14px;margin:17px 0 0;border-top:1px solid rgba(148,163,184,.12);color:#71829a;font-size:10px;line-height:1.5}.services{display:grid;gap:9px}.services div{display:grid;grid-template-columns:8px 1fr auto;align-items:center;gap:9px;padding:9px 0;border-bottom:1px solid rgba(148,163,184,.08)}.services b{font:8px 'JetBrains Mono',monospace;color:#b9c8d2}.services small{color:#2bb8b0;font:7px 'JetBrains Mono',monospace}.service-dot{width:6px;height:6px;border-radius:50%;background:#2bb8b0;box-shadow:0 0 8px #2bb8b0}.uptime{display:flex;align-items:baseline;gap:9px;margin-top:15px;color:#53647b;font:7px 'JetBrains Mono',monospace}.uptime strong{color:#d9e9e7;font:500 18px 'Space Grotesk',sans-serif;margin-right:auto}@media(max-width:1000px){.metrics{grid-template-columns:repeat(2,1fr)}.grid,.grid.lower{grid-template-columns:1fr}}@media(max-width:520px){.metrics{grid-template-columns:1fr 1fr}.ablation div{grid-template-columns:112px 1fr 42px}.ablation div:after{margin-left:-52px}}
</style>
