<script lang="ts">
	import WorkbenchPage from '$lib/components/dashboard/WorkbenchPage.svelte'; import MetricTile from '$lib/components/dashboard/MetricTile.svelte'; import InsightGraph from '$lib/components/dashboard/InsightGraph.svelte'; import BarContrib from '$lib/components/dashboard/BarContrib.svelte'; import RadarPlot from '$lib/components/dashboard/RadarPlot.svelte'; import ScatterField from '$lib/components/dashboard/ScatterField.svelte'; import Panel from '$lib/components/dashboard/Panel.svelte';
	const contrib=[{name:'mean RR interval',value:.31},{name:'ECG SQI',value:.2},{name:'pulse amplitude',value:-.14},{name:'SDNN / HRV',value:.1},{name:'SpO₂ stability',value:-.07}];
</script>
<svelte:head><title>Intelligence | NHM</title></svelte:head>
<WorkbenchPage eyebrow="02 / INTELLIGENCE" title="Make uncertainty legible." description="An inference workbench where anomaly score, signal quality, baseline drift, and feature contribution occupy the same visual field.">
	<div class="metrics"><MetricTile label="Anomaly score" value="0.08" detail="NORMAL / LIMIT 0.70" tone="amber" trend="−0.03" values={[.13,.12,.1,.11,.09,.08,.08]} /><MetricTile label="SQI-adjusted confidence" value="91" unit="%" detail="RAW 90% × SQI 84%" tone="cyan" trend="HIGH" values={[82,84,86,88,89,91]} /><MetricTile label="Baseline drift" value="+2.4" unit="%" detail="7 DAY PERSONAL WINDOW" tone="rose" trend="WATCH" values={[1,1.2,1.5,1.3,1.9,2.4]} /><MetricTile label="Uncertainty" value="0.06" detail="MC DROPOUT / LOW" values={[.1,.09,.08,.07,.06]} /></div>
	<div class="grid top"><Panel eyebrow="MODEL / HEALTH RADAR" title="Current physiological profile" note="5 DIMENSIONS"><RadarPlot /></Panel><Panel eyebrow="DETECTION / TIMELINE" title="Anomaly behavior" note="LAST 60 MIN"><InsightGraph title="Anomaly score" subtitle="NORMAL CLASSIFICATION" color="#fbbf24" value="0.08" kind="anomaly" /></Panel><Panel eyebrow="PERSONALIZATION / BASELINE" title="Learned envelope" note="30 DAYS"><InsightGraph title="Baseline evolution" subtitle="HR MEAN / 70 BPM" color="#38bdf8" value="+2.4%" kind="trend" /></Panel></div>
	<div class="grid split"><Panel eyebrow="CONFIDENCE / SQI GATE" title="Where does confidence hold?" note="EVENT SAMPLES"><ScatterField /><div class="legend"><span><i class="teal"></i> reliable sample</span><span><i class="rose"></i> low-confidence event</span><span><i class="amber"></i> SQI threshold</span></div></Panel><Panel eyebrow="EXPLAINABILITY / EVENT E002" title="Feature contribution" note="ISOLATION FOREST"><BarContrib features={contrib} maxAbs={.4} height={255} /><div class="interpretation"><span>INTERPRETATION</span><strong>Stable rhythm; no escalation.</strong><p>Mean RR and ECG quality pull the score down. The quality gate keeps low-quality windows from becoming false high-confidence events.</p></div></Panel></div>
	<div class="insight"><span>MODEL NOTE / SQI-AWARE</span><strong>Inference is only as trustworthy as the signal that feeds it.</strong><p>Raw model confidence is adjusted by overall SQI, matching the detector contract in <code>backend/ml/anomaly_detector.py</code>.</p></div>
</WorkbenchPage>
<style>
	.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.grid{display:grid;gap:8px;margin-top:8px}.grid.top{grid-template-columns:.8fr 1.1fr 1.1fr}.grid.split{grid-template-columns:1.1fr .9fr}.legend{display:flex;flex-wrap:wrap;gap:18px;padding-top:12px;border-top:1px solid rgba(148,163,184,.12);color:#64748b;font:8px 'JetBrains Mono',monospace}.legend i{display:inline-block;width:7px;height:7px;margin-right:5px;border-radius:50%}.teal{background:#2bb8b0}.rose{background:#fb7185}.amber{background:#fbbf24}.interpretation{margin-top:12px;padding-top:13px;border-top:1px solid rgba(148,163,184,.12)}.interpretation span{color:#2bb8b0;font:7px 'JetBrains Mono',monospace;letter-spacing:.13em}.interpretation strong{display:block;margin-top:7px;color:#dce9e8;font:500 17px 'Space Grotesk',sans-serif}.interpretation p,.insight p{margin:7px 0 0;color:#71829a;font-size:11px;line-height:1.55}.insight{display:grid;grid-template-columns:auto 1fr 1.1fr;align-items:center;gap:20px;margin-top:8px;padding:18px;border:1px solid rgba(43,184,176,.22);background:rgba(43,184,176,.05)}.insight>span{color:#2bb8b0;font:7px 'JetBrains Mono',monospace;letter-spacing:.13em}.insight strong{font:500 18px 'Space Grotesk',sans-serif}.insight p{margin:0}code{color:#a5b4fc;font:10px 'JetBrains Mono',monospace}@media(max-width:1050px){.metrics{grid-template-columns:repeat(2,1fr)}.grid.top,.grid.split{grid-template-columns:1fr 1fr}.grid.top>:first-child{grid-column:span 2}}@media(max-width:650px){.metrics,.grid.top,.grid.split{grid-template-columns:1fr}.grid.top>:first-child{grid-column:auto}.insight{grid-template-columns:1fr}}
</style>
